site_name: Winterbloom Helium User Guide
site_url: https://helium.wntr.dev
copyright: "© 2021 Winterbloom, Licensed under Creative Commons CC BY-SA 4.0"
repo_url: "https://github.com/wntrblm/Helium"
edit_uri: edit/main/user_guide/docs
theme:
    name: winterbloom
markdown_extensions:
    - admonition
    - def_list
    - attr_list
    - footnotes
    - toc:
          permalink: "#"
          toc_depth: 2-3
    - pymdownx.highlight:
          use_pygments: True
    - pymdownx.superfences
    - pymdownx.magiclink
    - pymdownx.tilde:
          subscript: true
    - md_in_html
    - markdown_link_attr_modifier:
          new_tab: "external_only"
          custom_attrs:
              referrerpolicy: "origin"
nav:
    - "User Guide": index.md
    - "Build Instructions":
        - "Kit": kit-build.md
        - "Self-sourced": self-source-build.md
